# Generated by Django 6.0.3 on 2026-03-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='instructor_notified',
            field=models.BooleanField(default=False),
        ),
    ]
